---
version: 3

images:
  base_image:
    name: ghcr.io/ansible/community-ansible-dev-tools:latest

dependencies:
  # Use python3
  python_interpreter:
    package_system: python3
    python_path: /usr/bin/python3

  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip

options:
  tags:
    - ansible_ee