---
version: 3

images:
  base_image:
    name: ghcr.io/ansible/community-ansible-dev-tools:latest

dependencies:
  # Use python3
  python_interpreter:
    package_system: python3
    python_path: /usr/bin/python3

  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system:
    - openssh-clients
    - sshpass
    - crypto-policies
    - crypto-policies-scripts

  python: requirements.txt

  galaxy: collections/requirements.yml

additional_build_files:
  - src: files/ssh_config_override
    dest: configs

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  prepend_final:
    - RUN mkdir -p /etc/ssh/ssh_config.d
    - COPY _build/configs/ssh_config_override /etc/ssh/ssh_config.d/custom_kex_override.conf
  append_final:
    - RUN update-crypto-policies --set LEGACY
    - RUN update-crypto-policies --show

options:
  tags:
    - ansible_ee
