---
- name: Change interface admin state
  hosts: "{{ switch | default('SWITCH1') }}"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Set interface state
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ interface }}"
            enabled: "{{ (port_status == 'no shut') | ternary(true, false) }}"
