---
- name: Change interface admin state
  hosts: "{{ switch | default('SWITCH1') }}"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Test SSH to host
      ansible.builtin.command:
        cmd: ssh -Q kex {{ hostvars[switch].ansible_host | default('SWITCH1') }}
      delegate_to: localhost
      changed_when: false

    - name: Make a test connection
      ansible.builtin.command:
        cmd: "ssh Test@{{ hostvars[switch].ansible_host | default('SWITCH1') }}"
      delegate_to: localhost
      changed_when: false

    - name: Set interface state
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ interface }}"
            enabled: "{{ (port_status == 'no shut') | ternary(true, false) }}"
