---
- name: Change interface admin state
  hosts: "{{ switch | default('SWITCH1') }}"
  gather_facts: false
  connection: network_cli

  vars:
    ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256'

  tasks:
    - name: Set interface state
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ interface }}"
            enabled: "{{ (port_status == 'no shut') | ternary(true, false) }}"
